nvim-neorocks/rocks.nvim

lua/rocks/internal-types.lua, lua/rocks/luarocks.lua, lua/rocks/operations.lua, lua/rocks/setup.lua, lua/rocks/state.lua, todos.norg
Note: This is stacked on top of #2.
Because #2 is from my fork, I can't point this PR to that branch.
Fixes #3.
=> fix(sync): do not attempt to remove dependencies

lua/rocks/commands.lua, lua/rocks/search.lua
- package names
- package versions
=> feat: name and version completions for `:Rocks install`

lua/rocks/luarocks.lua, lua/rocks/state.lua
This PR adds proper error propagation from async functions, allowing users to see when a run of a luarocks command goes wrong.
=> feat: add proper error propagation in async contexts

lua/rocks/init.lua
Add installation result detection in `bootstrap` to determine whether the status code is 0
=> feat(bootstrap): add Installation result detection

README.md, doc/rocks.txt, lua/rocks/commands.lua
Note: This is stacked on #41, to avoid merge conflicts
=> feat: add `:Rocks edit` command for opening `rocks.toml`

README.md, doc/rocks.txt, lua/rocks/commands.lua, lua/rocks/log.lua, lua/rocks/luarocks.lua, lua/rocks/operations.lua, lua/rocks/state.lua
Note that this is stacked on top of #63 
Test steps:
- Edit `rocks.toml`
- `:Rocks sync`
- `:Rocks log`
Closes #55.
=> feat: logging + `:Rocks log` command

README.md
=> docs(readme): add links to rocks-git and rocks-config modules

lua/rocks/config/internal.lua
Manual test: `:Rocks sync` still works
=> fix(api): ensure `get_rocks_toml` returns `RockSpec[]` tables

lua/rocks/runtime.lua
=> fix(runtime): variable naming conflict

doc/rocks.txt, lua/rocks/commands.lua, lua/rocks/runtime.lua
Fixes https://github.com/nvim-neorocks/rocks-git.nvim/issues/14
=>  feat(packadd): Fall back to builtin `packadd` if no rock is found.

installer.lua
=> fix(installer): disable line wrapping for option's windows

installer.lua
This contains two commits and needs a rebase merge
=> fix(installer): various error handling fixes

doc/rocks.txt, lua/rocks/api.lua, lua/rocks/runtime.lua
This is needed by rocks-dev.nvim.
=> feat(api): add `source_runtime_dir`

plugin/rocks.lua
=> feat: add support for `:checkhealth`

installer.lua
The luarocks bug has been fixed.
=> revert(installer): stay on old luarocks commit

lua/rocks/cache.lua, lua/rocks/constants.lua, lua/rocks/luarocks.lua, lua/rocks/operations/helpers.lua, lua/rocks/operations/init.lua, lua/rocks/state.lua
#194 wasn't merged into master
=> feat: search rocks-binaries-dev server if version is dev or scm

installer.lua
The change is self explanatory :p
=> fix(installer): remove unnecessary guards

doc/rocks.txt, lua/rocks/api/init.lua, lua/rocks/config/init.lua, lua/rocks/config/internal.lua, lua/rocks/operations/init.lua
This also fixes some type annotations.
Closes #195
=> feat(update): reinstall `dev` rocks by default

lua/rocks/adapter.lua, lua/rocks/operations/helpers.lua
=> fix: async initialise + cleanup tree-sitter parser symlink

README.md, doc/rocks.txt, lua/rocks/api/init.lua, lua/rocks/commands.lua, lua/rocks/operations/init.lua, lua/rocks/operations/parser.lua, spec/operations_parser_spec.lua
This allows the following commands:
```vim
:Rocks install neorg
:Rocks install neorg 8.0.0
:Rocks install neorg 8.0.0 opt=true
:Rocks install neorg opt=true 8.0.0
:Rocks install neorg opt=true version=8.0.0
:Rocks install neorg opt=true
...
```
=> feat(install): support passing args, like `opt=true`

nix/plugin-overlay.nix, plugin/rocks.lua
=> fix(loader): add entire luarocks lua path

.github/workflows/luarocks.yml, nix/plugin-overlay.nix, rocks.nvim-scm-1.rockspec
=> fix(dependencies): bump toml-edit to a working version

lua/rocks/loader.lua, plugin/rocks.lua, spec/loader_spec.lua
=> fix(loader): only enable luarocks loader for luarocks with lua 5.1

installer.lua
=> ref(installer): use dynamic home path instead of hardcoding it in the post-installation instructions

lua/rocks/log.lua, lua/rocks/operations/init.lua
=> feat: better error messages + less verbose log level

lua/rocks/operations/init.lua
=> feat(log): include error messages reported in UI

lua/rocks/operations/init.lua
This seems to have gotten lost.
Merging, as this is trivial.
=> fix(sync/ui): progess ui displayed forever

lua/rocks/health.lua, nix/plugin-overlay.nix
=> feat(health): check for nvim-treesitter conflicts

lua/rocks/operations/init.lua
Fixes https://github.com/nvim-neorocks/rocks-git.nvim/issues/34
=> fix(prune): need to prune twice for rocks-git to remove plugin

lua/rocks/operations/init.lua
=> feat(install): Error if trying to install lua rocks by owner/repo

README.md, doc/rocks.txt, flake.lock, flake.nix, lua/rocks/api/hooks.lua, lua/rocks/api/init.lua, lua/rocks/commands.lua, lua/rocks/config/init.lua, lua/rocks/init.lua, lua/rocks/log.lua, lua/rocks/operations/helpers.lua, nix/test-overlay.nix, spec/operations/helpers_spec.lua
=> feat(rocks.toml): support specifying extra luarocks `install_args`

lua/rocks/luarocks.lua
Fixes https://github.com/nvim-neorocks/rocks-treesitter.nvim/issues/18
=> fix: synchronize all luarocks CLI invocations

README.md, doc/rocks.txt, lua/rocks/api/init.lua, lua/rocks/cache.lua, lua/rocks/commands.lua, lua/rocks/operations/add.lua, lua/rocks/operations/prune.lua, lua/rocks/operations/update.lua, lua/rocks/types.lua, plugin/rocks.lua
Closes #420.
- Also exposes the `try_get_cached_outdated_rocks`, which modules like `rocks-edit.nvim` could use to improve performance (cc @vhyrro)
=> feat(update): `:Rocks update {rock}` alias for individual rocks

lua/rocks/adapter.lua, lua/rocks/init.lua, lua/rocks/operations/add.lua, lua/rocks/operations/helpers.lua, lua/rocks/operations/prune.lua, lua/rocks/operations/sync.lua, lua/rocks/operations/update.lua, lua/rocks/runtime.lua, spec/adapter_spec.lua
> [!IMPORTANT]
>
> When merging, rebase. Do not squash!
See commit messages.
Tested https://github.com/nvim-neorocks/rocks.nvim/pull/480/commits/090d424c7b746ee6bb7a2126ea56ee3ce5518d0f manually by deleting site symlinks and starting rocks.nvim.
Although: Thanks to https://github.com/nvim-neorocks/rocks.nvim/pull/480/commits/d82570799951c0cf8ceef7125c04d7526f4fd369, it didn't seem to occur anymore.
Initialising the site symlinks (with 27 rock installed) takes about 3.5 s on my machine.
So https://github.com/nvim-neorocks/rocks.nvim/pull/480/commits/090d424c7b746ee6bb7a2126ea56ee3ce5518d0f shaves off about 3.5 s per rock for sync/update operations :tada: 
It's still not close to the performance I'd like, but it's something.
=> Various site symlink improvements and fixes

README.md
=> docs(readme): update requirements

lua/rocks/adapter.lua
=> fix(windows): use junctions instead of symlinks

bootstrap.lua, doc/rocks.txt, installer.lua, lua/rocks/api/init.lua, lua/rocks/cache.lua, lua/rocks/config/internal.lua, lua/rocks/constants.lua, lua/rocks/init.lua, lua/rocks/luarocks.lua, lua/rocks/operations/helpers.lua, lua/rocks/state.lua, spec/config_spec.lua, spec/luarocks_config_spec.lua
> [!IMPORTANT]
>
> This PR contains 2 commits (one fix and one feature that are related).
> It should be rebased, not squashed.
Fixes https://github.com/nvim-neorocks/rocks-treesitter.nvim/issues/23
Fixes #487
Fixes #342
Closes #441
=> chore: some rocks-binaries improvements and fixes

lua/rocks/luarocks.lua
=> fix(windows): several terminal windows popping up

bootstrap.lua, installer.lua
=> chore(installer): better error messages

README.md
=> docs(readme): less confusing requirements section

lua/rocks/operations/sync.lua
=> fix(sync): wait for installed rocks.nvim modules to load

lua/rocks/operations/helpers/init.lua
=> fix(install): don't error if generating helptags fails
