- plugin/rocks.lua
This lets us reuse the keys for the completions.
In a follow-up, we could change the `command_tbl` to something like this:
```lua
command_tbl = {
install = {
command = function(_) ...end,
completions = function(arg_lead) 
-- run `luarocks query`
end,
},
}
```
(if it can be done without lagging neovim)
> refactor(commands): use table to map commands to implementations

- lua/rocks/init.lua
I added this in #3 and forgot to remove it again.
> fix: remove accidental bootstrap_dependencies call

- flake.lock
- flake.nix
- lua/rocks/init.lua
- nix/plugin-overlay.nix
- nix/test-overlay.nix
- rocks.nvim-scm-1.rockspec
Currently, you have to call `:lua require('rocks').setup()` for the plugin to initialize.
> build: neovim derivation with rocks.nvim for manual testing with nix

- lua/rocks/commands.lua
- lua/rocks/config/check.lua
- lua/rocks/config/internal.lua
- lua/rocks/constants.lua
- lua/rocks/fs.lua
- lua/rocks/health.lua
- lua/rocks/init.lua
- lua/rocks/internal-types.lua
- lua/rocks/luarocks.lua
- lua/rocks/operations.lua
- lua/rocks/search.lua
- lua/rocks/state.lua
- lua/rocks/types.lua
I updated the copyright notice of the source code headers to use the name of the neorocks organization, since this is no longer a private project under my profile
> docs: fix copyright notice in the source code files header

- nix/plugin-overlay.nix
- nix/test-overlay.nix
- rocks.nvim-scm-1.rockspec
We are using [nui.nvim](https://luarocks.org/modules/MunifTanjim/nui.nvim) to create the user interfaces, but the dependency is not declared in the luarocks manifests or the Nix flake (only in the internal bootstrapping process that is going to be deprecated later). This PR seeks to solve this inconsistency.
> feat: add nui.nvim dependency to the manifest

- .editorconfig
- CHANGELOG.md
- Makefile
- README.md
- installer.lua
- lua/rocks/constants.lua
- lua/rocks/init.lua
- lua/rocks/luarocks.lua
This PR adds a fully working installation process using a remote `:source` command invocation.
While there are still a few rough edges I believe it's a good enough MVP to push into main :)
> [FEATURE]: Implement an install script for `rocks.nvim`

- flake.nix
- nix/plugin-overlay.nix
This adds static type checking for neovim-nightly to our CI.
Note that I didn't add it as a pre-commit-hook to the Nix shell, because it can be quite slow.
> ci: add static type checking for neovim-nightly

- lua/rocks/config/check.lua
- lua/rocks/config/init.lua
- lua/rocks/config/internal.lua
- lua/rocks/luarocks.lua
Also added the `luarocks_binary` configuration option to the `config` module, which is added by the installer and we had forgotten to add it there :p
This fixes operations when luarocks was compiled by `rocks.nvim` as otherwise any `:Rocks` command will fail with a `ENOENT: no such file or directory` error message from the Neovim API when trying to execute `luarocks` commands.
> hotfix: do not hardcode luarocks binary in `luarocks.cli` function

- README.md
- flake.nix
- lua/nio/control.lua
- lua/rocks/commands.lua
- lua/rocks/internal-types.lua
- lua/rocks/operations.lua
- lua/rocks/state.lua
Test steps:
1, `:Rocks install plenary.nvim` (depends on `luassert`, which depends on `say`, ...) + `haskell-tools.nvim` + `neorg`
2. `:Rocks prune <tab>` -> Completion works as expected, without suggesting dependencies.
3. `:Rocks prune plenary.nvim` -> Uninstalls `plenary.nvim` and its dependencies.
4. `:Rocks prune <tab>` -> Shows completions for remaining rocks (`haskell-tools.nvim`, `neorg`).
> feat: `:Rocks prune` command to uninstall rocks and dependencies

- lua/rocks/operations.lua
- lua/rocks/search.lua
- lua/rocks/state.lua
Should prevent errors like this one:
Manual test steps:
- Tested that `:Rocks install` and `:Rocks prune` still work (using the nix derivation).
> fix(internal): use `vim.empty_dict` for better vimscript interop

- .github/workflows/luarocks.yml
- README.md
- flake.lock
- flake.nix
- lua/rocks/commands.lua
- lua/rocks/fzy.lua
- lua/rocks/search.lua
- lua/rocks/state.lua
- nix/plugin-overlay.nix
- nix/test-overlay.nix
- rocks.nvim-scm-1.rockspec
Uses `fzy` to implement fuzzy completions for rocks in the `:Rocks install` command.
Manual test:
```console
nix run .#neovim-with-rocks
```
```vim
:Rocks ill<TAB>
```
Completes to `:Rocks install`.
```vim
:Rocks install norg<TAB>
```
Shows `neorg` as the first completion result.
Install `neorg` if not installed.
```vim
:Rocks prune norg<TAB>
```
Shows `neorg` as the first completion result.
> feat(commands): fuzzy completions for `:Rocks install [rock]`

- nix/init.lua
- nix/plugin-overlay.nix
The test derivation only lets us install/prune plugins.
This adds an `init.lua` that lets us use the installed plugins with the test dervation.
Test steps:
```console
nix run .#nvim-with-rocks
```
```vim
:Rocks install neorg
" wait for install to finish
:q
```
```console
nix run .#nvim-with-rocks
```
```vim
:lua =require('neorg')
```
-> prints the neorg module table
> chore(nix): add init.lua to load rocks to nvimrocks derivation

- .editorconfig
- .github/workflows/luarocks.yml
- .neoconf.json
- flake.lock
- flake.nix
- lua/rocks/constants.lua
- lua/rocks/operations.lua
- nix/plugin-overlay.nix
- nix/test-overlay.nix
- rocks.nvim-scm-1.rockspec
This uses the new `fidget.progress` API for reporting operations progress.
It feels a bit more modern than the current `nui` implementation, with the ability to report progress as a percentage (`update`, `sync`, ...), and show signs of life with the spinner animation.
For now, error handling isn't that advanced.
I plan on keeping track of errors with a log file (#55).
> feat(ui): use fidget.nvim for progress reports

- lua/rocks/commands.lua
- lua/rocks/luarocks.lua
- lua/rocks/operations.lua
- lua/rocks/state.lua
> fix(sync): prevent luarocks install tree race conditions

- doc/rocks.txt
- lua/rocks/api.lua
This PR modifies the existing `get_rocks_toml` function (which earlier retrieved the path) to now retrieve
the parsed TOML file. The old function has now been moved to `get_rocks_toml_path`, which naturally returns the path.
This is to allow rocks modules to easily access the contents of the rocks.toml file without having to worry about using their own parsers.
> refactor(api): `get_rocks_toml` -> `get_rocks_toml_path`

- .gitignore
- CONTRIBUTING.md
- flake.nix
This allows us to run `luarocks test` with Neovim as the interpreter from within the devShell.
> chore(nix): use test suite as base for devShell

- doc/rocks.txt
- lua/rocks/config/check.lua
- lua/rocks/config/init.lua
- lua/rocks/config/internal.lua
- lua/rocks/operations.lua
This PR adds freshly installed plugins to the runtimepath so they can be used right away.
TODOs:
This approach theoretically adds more than usually required to the RTP (as by default we use a glob over all installed plugins), however this is only for the current session (which is a good tradeoff in my opinion) and makes sure everything works smoothly.
> feat: auto add newly installed plugins to the RTP

- installer.lua
- lua/rocks/config/internal.lua
- nix/init.lua
- plugin/rocks.lua
This is in preparation for #86.
For now, no behaviour has changed. `rocks.nvim` still adds all plugins to the rtp on startup.
> refactor(installer): only add rocks.nvim to rtp in install script

- doc/rocks.txt
- lua/rocks/api.lua
- lua/rocks/log.lua
- lua/rocks/operations.lua
- nix/test-overlay.nix
... in preparation for #81.
This is ready to be reviewed, but I'd prefer to leave it as a draft and not to merge it until we have a basic working implementation of a module that uses this API.
I initially wanted the API to allow hooking into the `update`, `sync` and `prune` commands.
But after playing around with the idea, I think `sync` is enough. 
Hooking into `update` and `prune` might be a bad idea, for the following reasons:
- `update` uses the luarocks state to determine the outdated rocks, and then updates the rocks.toml (parsed with `toml-edit`).
Hooking into `update` would require parsing the config with `toml`, and potentially allowing to update the config with `toml-edit`.
This adds a whole lot of complexity. 
- Like `update`, `prune` parses and modifies the config with …
> feat(api): allow external modules to hook into `:Rocks sync`

- installer.lua
- nix/init.lua
- plugin/rocks.lua
This reverts commit c1ef18775abe8d56c85d5ee40ea7ca6f4307f941.
The change prevented files in `plugin` directories, etc. from being sourced.
> revert(installer): only add rocks.nvim to rtp in install script (#88)

- lua/rocks/operations.lua
> fix(sync): error when downgrading from `scm`/`dev` versions

- .github/workflows/luarocks.yml
- flake.lock
- flake.nix
- lua/rocks/operations.lua
- nix/plugin-overlay.nix
- rocks.nvim-scm-1.rockspec
Manual test steps:
- `nix run .#neovim-with-rocks -- -c "Rocks edit"`
- Add the following entry: `"haskell-tools.nvim" = { version = "3.0.0", opt = true }`
- `:Rocks sync`
- `:Rocks update`
-> Updates the entry to `"haskell-tools.nvim" = { version = "3.1.1", opt = true }`
> fix(update,install): rocks.toml entries coerced to strings

- lua/rocks/operations.lua
- lua/rocks/runtime.lua
- lua/rocks/state.lua
`pcall` unwinds the stack when it fails, so we lose the stack trace. Moving the code to a different
coroutine allows us to notify/log the stack trace
that we're actually interested in.
> fix: better stack traces

- installer.lua
https://github.com/nvim-neorocks/rocks.nvim/blob/4f9086551bd9af0eeead663ebed54eaddf67f1e3/installer.lua#L170
Lua has no mustache.
Replace all with `%s`.
But even if I replace all with `%s`, the error message is pretty difficult to read due to the color sequences in the output.
I've added a wrapper function to remove the color sequences for a better visibility.
> fix(installer): remove color seqence from shell output

- README.md
When lua and luajit is not installed via the system package manager, luarocks build script 
fails to detect the lua runtime, which results in a fail. 
Usually, we can `./configure` with options such as `--with-lua` ([cli options](https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix#customizing-your-settings)), but as this is run in the background, I cannot edit these options, or I would need to add a new field in the UI which is kinda hassle. 
Luarocks build scripts uses variables such as `LUA_DIR`, so we can trick the script by providing these varibles from outside. 
To workaround this issue, I added a `[!TIP]` in the README for other people who came across the same issue.
---
> [!TIP]
>
> In order to configure luarocks installation to use a specific lua install, …
> docs(readme): add tip to configure luarocks install with envvars

- .github/workflows/release-please.yml
This should ensure that the luarocks upload action is triggered automatically on release
> ci: add signoff input to release-please workflow

- .github/workflows/update.yml
This updates the neovim version, etc, against which we run tests.
> ci: auto-update the flake.lock

- doc/rocks.txt
- lua/rocks/config/check.lua
- lua/rocks/config/init.lua
- lua/rocks/config/internal.lua
- lua/rocks/operations.lua
This PR also adds a new configuration option called `generate_help_pages`, which defaults to `true`.
> feat: generate plugins help pages tags on install/update

- lua/rocks/luarocks.lua
- nix/plugin-overlay.nix
> fix(luarocks): make sure `LUAROCKS_CONFIG` is unset

- .gitignore
- .luarc.json
- flake.lock
- flake.nix
This is for the nix devShell:
It generates a `.luarc.json` with all the luarocks dependencies and symlinks it.
The resulting config is the same one used by the type checker in CI.
The resulting json looks something like this:
```json
{
"Lua": {
"diagnostics": {
"disable": [],
"libraryFiles": "Disable"
},
"workspace": {
"ignoreDir": [
".git",
".github",
".direnv",
"result",
"nix",
"doc"
],
"library": [
"/nix/store/41s4jsbz8jwal2smd0qy6rfi0cnl2mbs-neovim-unwrapped-848fc8e/share/nvim/runtime/lua",
"/nix/store/vbq303yxcq07aqxmlhk57nkgr3hzyl49-vimplugin-neodev.nvim-2024-02-16/types/nightly",
"/nix/store/s6nhgga8p7mvkq5ksj1mrilazc92cby0-lua5.1-toml-edit-0.1.5-1/lib/lua/5.1/",
"/nix/store/g215i1s1phrhyfrrgqw748a1l0xlz6gv-lua5.1-toml-0.3.0-0/lib/lua/5.1/", …
```
> build(nix): remove .luarc.json and generate one in nix devShell

- lua/rocks/operations.lua
This PR completely removes the error message when a malformed rock is encountered. This error is fairly redundant - it occurs when a version key could not be found, but there are many cases where you could be doing this on purpose - i.e. you are specifying a `dir` key or a `git` key.
It might make sense to add an option to issue warnings on invalid rocks if users want to be extra safe, but I'm not sure if we want that right now.
(cc @mrcjkb)
> fix: ignore malformed rocks

- installer.lua
This should reduce the amount of time it takes to clone.
> perf(installer): Use `--filter=blob:none` when cloning luarocks

- installer.lua
Fixes #199 
Tested on Fedora 39 with `NVIM v0.10.0-dev+2606-gc0549b9c4`
> revert(installer): use `vim.o.sh` instead of `'sh'`

- README.md
This feels a bit more streamlined...
> docs(readme): move tree-sitter section to intro subsection

- .editorconfig
- README.md
- doc/rocks.txt
- lua/rocks/config/init.lua
- lua/rocks/config/internal.lua
- lua/rocks/luarocks.lua
- plugin/rocks.lua
> feat(loader): support multiple versions of the same dependency

- .github/workflows/luarocks.yml
- flake.nix
- lua/rocks/config/internal.lua
- lua/rocks/health.lua
- nix/plugin-overlay.nix
- rocks.nvim-scm-1.rockspec
Fixes #228.
Blocked until toml-edit 0.3.3 has been pushed to luarocks
> refactor: replace `toml` dependency with `toml-edit` for decoding

- lua/rocks/operations/helpers.lua
- lua/rocks/operations/init.lua
Now that `nio.tests` work with busted, we can use
`nio.control.Future` directly, and don't need to use `vim.SystemObj:wait()`.
> refactor: remove `Future` wrapper type

- doc/rocks.txt
- lua/rocks/api/hooks.lua
- lua/rocks/runtime.lua
- plugin/rocks.lua
Closes #237.
This fixes the loading order issue (e.g. colorschemes) for rocks-config.nvim:
1. Append start plugins to the rtp
2. Call preload hooks -> rocks-config.nvim
3. Source plugin directories
With this, I don't think rocks-config needs to worry about providing `before` or `after`  config mechanisms.
> fix(runtime): append start plugins to rtp before calling preload hooks

- installer.lua
Fixes #269.
Relates to #266 - If people use the same config on multiple platforms, the init.lua snippet should support that by default.
> fix(installer): update `package.cpath` for all platforms

- installer.lua
- plugin/rocks.lua
The neovim version requirement in the readme can be overlooked, leading to people opening issues.
> feat: add version check to installer and plugin script

- README.md
- doc/rocks.txt
- lua/rocks/api/init.lua
- lua/rocks/commands.lua
- lua/rocks/operations/init.lua
- spec/operations/pin_commands_spec.lua
> feat: `Rocks [pin|unpin] {rock}` command

- lua/rocks/luarocks.lua
Related to #307.
This doesn't seem to actually fix the issue.
Maybe due a libuv or neovim bug, in which the process isn't actually detached?
I think this is what we want in case it does one day get fixed.
> chore(operations): detach luarocks process

- lua/rocks/luarocks.lua
If exiting neovim duringa `:Rocks sync`, a lockfile.lfs may be left behind in the rocks_dir.
We already have an in-memory locking mechanism, so there's no need to use the luarocks lock file, which currently needs to be removed manually.
> fix(luarocks): add `--force-lock` flag

- lua/rocks/operations/init.lua
> fix(operations): error if 'rocks' or 'plugin' key missing in rocks.toml

- lua/rocks/luarocks.lua
- lua/rocks/operations/init.lua
- spec/operations/bulk_install_spec.lua
Stacked on #323.
Fixes https://github.com/nvim-neorocks/rocks-git.nvim/issues/28
> fix(operations): race conditions when running commands concurrently

- lua/rocks/operations/init.lua
- spec/operations/sync_spec.lua
Fixes #77.
Note: This also removes the progress percentage from `:Rocks sync`, which is impossible to estimate correctly and is just confusing when estimated incorrectly.
> fix(sync): prune all rocks that can be pruned in a single sweep

- doc/rocks.txt
- lua/rocks/config/init.lua
- lua/rocks/config/internal.lua
> feat: allow overriding luarocks config

- lua/rocks/adapter.lua
- lua/rocks/operations/helpers.lua
- spec/adapter_spec.lua
Fixes #354.
Existing installations may still have a `parser` symlink in the `rocks_rtp` directory (typically `~/.local/share/rocks/rocks_rtp`) after upgrading, which will need to be removed manually.
It doesn't cause any actual issues (besides duplicated captures, visible with `:Inspect`), which is why I chose not to add logic for removing it (as this adds overhead).
> fix(tree-sitter): stop creating now redundant `rocks_rtp/parser` symlink

- lua/rocks/operations/helpers.lua
Fixes #351 
Note: This doesn't actually work with luarocks 3.11.0, see https://github.com/luarocks/luarocks/issues/1657
> fix(operations): always force reinstalls if rocks are already installed

- README.md
Installing lua 5.1 using `brew install lua@5.1` results in an error due to the formula being disabled. Instead macOS brew users can do `brew install luajit`
> docs(readme): add luajit as requirement for homebrew users 

- .github/workflows/luarocks.yml
- bootstrap.lua
- doc/rocks.txt
- flake.lock
- installer.lua
- lua/rocks/config/init.lua
- lua/rocks/config/internal.lua
- lua/rocks/loader.lua
- lua/rocks/luarocks.lua
- nix/plugin-overlay.nix
- nix/test-overlay.nix
- plugin/rocks.lua
- rocks.nvim-scm-1.rockspec
- spec/adapter_spec.lua
- spec/loader_spec.lua
- spec/operations/bulk_install_spec.lua
- spec/operations/helpers_spec.lua
- spec/operations/install_update_spec.lua
- spec/operations/pin_commands_spec.lua
- spec/operations/pin_spec.lua
- spec/operations/sync_spec.lua
> feat: manage luarocks installation as rockspec dependency

- lua/rocks/luarocks.lua
Fixes #373.
If these variables are set (e.g. by homebrew), the bundled luarocks install may not find its libraries.
> fix(luarocks): set `LUA_PATH` and `LUA_CPATH`

- lua/rocks/adapter.lua
This fixes a bug (parially introduced in #355)
I was mistaken in my assumption that Neovim makes  `site/pack/*/opt` packages' rtp directories  available without calling `packadd!`.
Apparently it only does that for colorschemes.
Since rocks.nvim initialises as a `plugin` script, during the `:h load-plugins` phase of Neovim's initialisation, we can safely call `packadd!` (with a bang) for all installed rocks, without causing Neovim to source any plugin scripts.
This makes all rtp directories (e.g. `autoload`) available, so luarocks plugins can have vimscript plugins like `repeat.vim` as dependencies.
> fix(runtime): make sure dependencies' rtp directories can be used

- lua/rocks/operations/init.lua
Fixes #380.
If a rocks.toml entry was set to an older version than a rock that is already up-to-date, then `:Rocks update` wouldn't update it and the next `:Rocks sync` would downgrade the rock.
> fix(update): set version of all installed rocks.toml entries

- lua/rocks/operations/helpers.lua
- lua/rocks/operations/init.lua
Fixes https://github.com/nvim-neorocks/rocks-git.nvim/issues/34
> fix(prune): delegate to extensions' handlers

- doc/rocks.txt
- lua/rocks/api/hooks.lua
- lua/rocks/config/internal.lua
- spec/hook_spec.lua
This refines the preload hook API to support different types of hooks.
For now, the following are supported:
- `RockSpecModifier`s, which allow extensions to modify the hooks that rocks.nvim sees.
- rocks-lazy.nvim will be able to use this to let rocks.nvim know that a plugin is `opt`, without users having to set the `opt` field.
- This could potentially also be useful for the rocks-nix.nvim module I'm planning.
- `Action`s, which is what we have already implemented in rocks-config.nvim, only that it can now take the (potentially modified) `user_rocks: RockSpec[]` as a parameter, so that rocks-config.nvim doesn't have to read it from the rocks.toml again.
The modifier does not do anything with the `MutRocksTomlRef` (the one we use to write to rocks.toml on install, update, ...). I think …
> feat(api): `RockSpecModifier` preload hooks

- lua/rocks/operations/init.lua
- lua/rocks/state.lua
> refactor(sync): extract state.out_of_sync_rocks

- .github/workflows/docgen.yaml
- Makefile
- doc/rocks.txt
- flake.nix
- lua/rocks/config/init.lua
tried to harmoinze the display of defaults as well
> doc: add default for generate_help_pages

- lua/rocks/health.lua
Fixes #429.
I think the way the fix was done is simple yet works well, but if there are any suggestions it will be more than welcome :)
> fix(health): do not produce duplicated messages when there are no errors in the `rocks.toml` file

- doc/rocks.txt
- flake.nix
- lua/rocks/config/init.lua
- lua/rocks/log.lua
I first wanted to document vim.g.rocks_nvim._log_level but it is ignored after startup so it didn't seem like a good idea after all.
I've instead exposed log.set_level. The description of the function is ignored for some reason :s 
I've added doc tags for `vim.g.rocks_nvim`
> docs(vimdoc): log level

- lua/rocks/operations/init.lua
> feat(install): improve 'dev' version search prompt

- plugin/rocks.lua
To help debug/diagnose if config is correctly set. It can be deceiving in case vim.g.rocks_nvim gets changed later.
Which is why at first I thought of passing the luarocks config via the command line instead of the environment but luarocks still doesn't support it: https://github.com/luarocks/luarocks/issues/1086
This looks like a good compromise.
> feat(log): trace luarocks_config path

- README.md
- doc/rocks.txt
- lua/rocks/commands.lua
- lua/rocks/operations/helpers.lua
- lua/rocks/operations/init.lua
- lua/rocks/state.lua
- spec/operations/helpers_spec.lua
- spec/operations/install_update_spec.lua
Closes #191 
Stacked on #439 (already reviewed by @teto) to avoid merge conflicts.
> feat: prompt to update plugins with breaking changes + options to skip prompts with `!`

- .github/workflows/integration.yml
- .gitignore
- README.md
- doc/rocks.txt
- flake.nix
- lua/rocks/commands.lua
- lua/rocks/config/init.lua
- lua/rocks/config/internal.lua
- lua/rocks/loader.lua
- lua/rocks/luarocks.lua
- lua/rocks/operations/helpers.lua
- lua/rocks/operations/init.lua
- lua/rocks/state.lua
- nix/test-overlay.nix
- plugin/rocks.lua
- spec/loader_spec.lua
- spec/luarocks_config_spec.lua
- spec/operations/helpers_spec.lua
- spec/operations/install_update_spec.lua
Stacked on #442 
This adds a solution for #443 by making it easier to defend the default luarocks config.
You can add extra directories to search for binaries via
```lua
vim.g.rocks_nvim = {
-- ...
---@type string | table file path or config table to extend the default with
luarocks_config = {
external_deps_dirs = { "/some/path" },
},
}
```
See https://github.com/luarocks/luarocks/wiki/Config-file-format for details.
> feat: support extending the default luarocks config

- lua/rocks/operations/sync.lua
This bug was introduced by the refactor in commit 704940f43c600f95a5d4a5177b918af849b3a150, which changed external_actions from a list to a key-value table. However, when iterating through external_actions, we still use ipairs which results in no values.
This caused rocks-git to not run sync actions on any of its rocks, so e.g. adding `fzf-lua = { git = "ibhagwan/fzf-lua" }` to your rocks.toml then running `:Rocks sync` would not actually install fzf-lua.
> [!NOTE]
> On my machine, rocks-git properly installs its rocks after a fresh bootstrap of rocks.nvim and an initial `:Rocks sync`, but I'm not sure why it works on the first run. After that, rocks-git doesn't run its sync callback due to the bug this PR fixes.
> fix: external sync actions not running

- README.md
- doc/rocks.txt
- lua/rocks/meta.lua
- lua/rocks/operations/helpers.lua
- nix/test-overlay.nix
- spec/operations/install_update_spec.lua
See also: #489
This would allow users of plugins that require an impure autoload function to be invoked to do so.
For example:
```lua
vim.api.nvim_create_autocmd("User", {
pattern = "RocksInstallPost",
callback = function(ev)
if ev.data.installed.name == "firenvim" then
vim.cmd.call("firenvim#install(0)")
end
end,
})
```
> feat: trigger `RocksInstallPost` user event after install/update

- doc/rocks.txt
- lua/rocks/cache.lua
- lua/rocks/meta.lua
Needed for 
- https://github.com/nvim-neorocks/rocks-edit.nvim/pull/5
> feat(api): emit user events for cache updates

- lua/rocks/fs.lua
On Windows, `rocks.toml` was getting erased every time rocks tried to write to it.
It seems to have been caused by using pipes (perhaps because the behaviour on Linux is different to that of Windows).
This PR removes the pipe and uses `uv.fs_write(file, ...)` instead.
Resolves #516
> fix(windows): rocks.toml getting wiped on save

- flake.lock
- lua/rocks/operations/sync.lua
> fix: adapt to nvim 0.11 breaking `vim.version.parse` change

- doc/rocks.txt
- lua/rocks/api/init.lua
- lua/rocks/config/init.lua
- lua/rocks/config/internal.lua
- lua/rocks/constants.lua
- lua/rocks/operations/add.lua
- lua/rocks/operations/handlers.lua
- lua/rocks/operations/helpers.lua
- lua/rocks/operations/sync.lua
- lua/rocks/operations/update.lua
- spec/operations/helpers_spec.lua
Closes #365 
This provides a function that extensions can invoke to install or remove a luarocks stub, in order to trick luarocks into thinking a luarocks package is installed.
That way, plugins managed by extensions like rocks-git or rocks-dev can be recognised by luarocks as being installed, if other luarocks packages depends on them.
TODO:
Requires the following experimental feature to be enabled:
```lua
vim.g.rocks_nvim = {
-- ...
experimental_features = {
"ext_module_dependency_stubs",
},
}
```
and up-to-date rocks.nvim extensions.
> feat(experimental): a way to recognise plugins managed by extensions as dependencies

- lua/rocks/config/internal.lua
The constants `DEFAULT_ROCKS_SERVERS` and `DEFAULT_DEV_SERVERS` are tables and the `get_servers`/`get_dev_servers` can return these values meaning that the exact table instance will be returned, not a copy. This means that if the returned table instance is modified, the constants will also be modified. The `get_all_servers` function uses `vim.list_extend` which will modify the table of the first argument and so the `DEFAULT_ROCKS_SERVERS` list will continue to grow each time this function is called appending the dev servers each time. 
*May want to consider returning a copy of the constant tables OR just note to never modify the returned table values*
For some reason, this was actually causing an issue when trying to install some rocks because it would actually prioritize the luarocks …
> fix: stop luarocks server list from being overwritten

- lua/rocks/adapter.lua
- plugin/rocks.lua
> fix: add tree-sitter parsers to the runtimepath asap

- bootstrap.lua
- installer.lua
Should hopefully fix #568.
@ambaradan would you mind testing with the changes in this PR? :pray:
> fix(installer/bootstrap): pin luarocks to v3.11.1

- lua/rocks/adapter.lua
- lua/rocks/operations/helpers/init.lua
- lua/rocks/runtime.lua
> fix: attempt to concatenate field version (a `nil` value) on install

- lua/rocks/operations/helpers/init.lua
- lua/rocks/operations/helpers/multi_mut_rocks_toml_wrapper.lua
- spec/operations/helpers_spec.lua
Fixes an issue with the config_path option on installs (NOTE: this only affected the new config_path feature added last PR and not anything else). This was meant to be committed as part of the last PR but I had stashed these changes temporarily while testing a slightly different implementation and then forgot to re-apply the stashed changes afterwards (I apologize for this).
The original intention was that when you provided a config_path to the `parse_rocks_toml` function, it would add the import to the base config and then provide you a wrapper object which wrapped both the base config and the newly created import config so that you could write both at once when done updating. The issue with this is that the goal of the config_path option is so that you could make changes ONLY to the …
> fix: make sure config_path option for installs updates correct config

- lua/rocks/operations/sync.lua
> fix(sync): [regression] load rocks.nvim modules before trying to use them

- doc/rocks.txt
- lua/rocks/config/init.lua
- lua/rocks/config/internal.lua
- lua/rocks/runtime.lua
> feat: option to auto-sync on startup

- README.md
Hi,
this PR tries to:
- make the bootstrapping snippet work a bit nicer with lua-language-server. lua lsp will complain about the use of `vim.fn.stdpath` in `vim.fs.joinpath` since it can return `string[]` and will throw a warning. The fix is telling it to treat the `stdpath` call as a string.
- make the bootstrapping snippet less intimidating by reducing is sice in LOC
- remove redundant `vim.fs.normalize` call (`vim.fs.joinpath` already does that`)
- move the `vim.v.shell_error` check in the same branch as a "sanity check". It is nitpicking but, as is it right now, this can be trigger by _any_ `vim.fn.system` or `:!` gone wrong in the user configuration and moving it to the same branch as the `vim.fn.system` call that clones the repo this can make life much saner to user.
> docs(readme): make bootstrap snippet work well with lua-language-server

- lua/rocks/log.lua
to help troubleshoot perf issues
Before:
===
TRACE | 2025-03-13 19:10:31 | /home/teto/rocks.nvim/lua/rocks/loader.lua:23 | Enabling luarocks loader TRACE | 2025-03-13 19:10:32 | /home/teto/rocks.nvim/lua/rocks/commands.lua:281 | Creating commands TRACE | 2025-03-13 19:10:32 | /home/teto/rocks.nvim/plugin/rocks.lua:39 | Appending luarocks binary directory to the system path TRACE | 2025-03-13 19:10:32 | /home/teto/rocks.nvim/lua/rocks/api/hooks.lua:72 | Running preload hooks DEBUG | 2025-03-13 19:10:32 | /home/teto/rocks.nvim/lua/rocks/adapter.lua:42 | Symlink directory lua exists already. TRACE | 2025-03-13 19:10:32 | /home/teto/rocks.nvim/lua/rocks/runtime.lua:72 | Sourcing start plugins ===
After:
====
TRACE | 2025-03-13 19:04:08.941 | /home/teto/rocks.nvim/lua/rocks/loader.lua:23 | …
> feat(log): include milliseconds in timestamp

- installer.lua
I was running into [this issue](https://github.com/luarocks/luarocks/issues/1797) in luarocks while trying to install via the installer.lua script. Later in that issue they fixed it in 3.12.0. 
I used 3.12.2 to install on my machine (Fedora 42) and everything appears to be functioning. I know you are working on getting Lux working. But figured an intermediate fix would be nice.
> build: update luarocks version in install script
